Fixed local copy and general tidy

diff --git a/dist/pub b/dist/pub
--- a/dist/pub
+++ b/dist/pub
@@ -1,35 +1,59 @@
 #!/bin/bash
 
 
-# Define backwards_cp which switches source and destination
-_backwards_cp() {
-    cp "$2" "$1"
-}
-
+# Subcommand: version
 version() {
     echo "$PUB_VERSION"
 }
 
-# CONFIG
+# Subcommand: update
+update() {
+    echo "[*] UPDATE..."
+    if [ -f "/usr/local/bin/pub" ]; then
+        echo "[*] Updating pub... requires sudo!"
+        $FETCH_CMD "/tmp/pub" "$URL_PUB"
+        echo "[*] Installing to path"
+        sudo mv /tmp/pub /usr/local/bin/pub
+        echo "[*] Setting executable permissions"
+        sudo chmod +x /usr/local/bin/pub
+        echo "[*] Setting executable ownership"
+        sudo chown root:root /usr/local/bin/pub
+    else
+        echo "[!] Could not find /usr/local/bin/pub. Exiting."
+        exit 1
+    fi
+}
+
+# Subcommand: remove
+remove() {
+    echo "[*] REMOVE..."
+    if [ -f "/usr/local/bin/pub" ]; then
+        echo "[*] Removing pub... requires sudo!"
+        sudo rm -f "/usr/local/bin/pub"
+    else
+        echo "[!] Could not find /usr/local/bin/pub. Exiting."
+        exit 1
+    fi
+}
+
+# Subcommand: config
 config() {
+    echo "[*] CONFIG..."
     local subcommand=$1; shift
     # Check if the subcommand is a valid function and call it
     if type "config__$subcommand" >/dev/null 2>&1; then
         "config__$subcommand" "$@"
     else
         echo "[!] Invalid subcommand argument: $subcommand. Exiting."
+        echo "[!] Valid arguments: update install aliases functions gitconfig tmux"
         exit 1
     fi
 }
 
-config__update() {
-  command echo "config__update"
-}
-
 config__install() {
-    config__aliases
     config__functions
-    config__gitconfig
+    config__aliases
+    config__git
     config__tmux
 }
 
@@ -59,7 +83,7 @@ config__aliases() {
     fi
 }
 
-config__gitconfig() {
+config__git() {
     echo "[*] Configuring git..."
     $FETCH_CMD "$HOME/.gitconfig" "$URL_GITCONFIG"
 }
@@ -71,46 +95,17 @@ config__tmux() {
     $FETCH_CMD "$HOME/.tmux/homelab" "$URL_TMUX_HOMELAB"
 }
 
-# INSTALL
+# Subcommand: install
 install() {
-    echo "update"
+    echo "[*] INSTALL..."
 }
 
-# ENTRYPOINT
+# HELPERS
 
-# Check last argument is not the script itself
-# If it is, then we are being sourced, so just load functions and return
-[[ $_ != $0 ]] && return
-
-PUB_VERSION=""
-
-PUB_URL="https://pub.thomaslaurenson.com"
-IS_LOCAL=true
-if [ "$IS_LOCAL" = true ]; then
-    cd "$(dirname "$0")" || exit 1
-    PUB_URL="../dist"
-fi
-
-URL_ALIASES="$PUB_URL/config/aliases"
-URL_FUNCTIONS="$PUB_URL/config/functions"
-URL_GITCONFIG="$PUB_URL/config/gitconfig"
-URL_TMUX_CONF="$PUB_URL/config/tmux/tmux.conf"
-URL_TMUX_CER="$PUB_URL/config/tmux/cer"
-URL_TMUX_HOMELAB="$PUB_URL/config/tmux/homelab"
-
-# Determine fetch command
-if [ "$IS_LOCAL" = true ]; then
-    FETCH_CMD="_backwards_cp"
-elif command -v curl &> /dev/null; then
-    FETCH_CMD="curl -s -o"
-elif command -v wget &> /dev/null; then
-    FETCH_CMD="wget -q -O"
-else
-    echo "[!] No fetch command found... Exiting"
-    exit 1
-fi
-
-valid_subcommands=("config" "install" "version")
+# Define backwards_cp which switches source and destination
+_bcp() {
+    cp "$2" "$1"
+}
 
 # Function to check if an element is in an array
 _is_valid_subcommand() {
@@ -123,11 +118,50 @@ _is_valid_subcommand() {
     return 1
 }
 
+# ENTRYPOINT
+
+# Check last argument is not the script itself
+# If it is, then we are being sourced, so just load functions and return
+[[ $_ != "$0" ]] && return
+
+PUB_VERSION=""
+
+BASE_URL="https://pub.thomaslaurenson.com"
+
+# Toggle to use local files for testing
+IS_LOCAL=false
+if [ "$IS_LOCAL" = true ]; then
+    cd "$(dirname "$0")" || exit 1
+    BASE_URL="../dist"
+fi
+
+URL_PUB="$BASE_URL/pub"
+URL_ALIASES="$BASE_URL/config/aliases"
+URL_FUNCTIONS="$BASE_URL/config/functions"
+URL_GITCONFIG="$BASE_URL/config/gitconfig"
+URL_TMUX_CONF="$BASE_URL/config/tmux/tmux.conf"
+URL_TMUX_CER="$BASE_URL/config/tmux/cer"
+URL_TMUX_HOMELAB="$BASE_URL/config/tmux/homelab"
+
+# Determine fetch command to use
+if [ "$IS_LOCAL" = true ]; then
+    FETCH_CMD="_bcp"
+elif command -v curl &> /dev/null; then
+    FETCH_CMD="curl -s -o"
+elif command -v wget &> /dev/null; then
+    FETCH_CMD="wget -q -O"
+else
+    echo "[!] No fetch command found... Exiting"
+    exit 1
+fi
+
+valid_subcommands=("update" "remove" "config" "install" "version")
+
 # Check a valid subcommand was passed
 subcommand=$1
 if ! _is_valid_subcommand "$subcommand"; then
     echo "[!] Invalid subcommand: $subcommand"
-    echo "[!] Valid subcommands: ${valid_subcommands[@]}"
+    echo "[!] Valid subcommands: ${valid_subcommands[*]}"
     echo "[!] Exiting."
     exit 1
 fi
